//! **The join-toll theorem: the twist operation is toll-cheap, so polynomial toll is closed
//! under it.**
//!
//! The family lattice is generated by the Shannon JOIN (L14): `F₀ ⋈ F₁` glues an `n`-cover of the
//! `x = 0` face to an `n`-cover of the `x = 1` face. The join operation itself cannot be the
//! obstacle to polynomial toll, because it is provably additive:
//!
//!   **Theorem (join adds constant toll).** A DAG certificate of `F₀ ⋈ F₁` is built by ONE fresh
//!   root branching on the split variable into the certificates of `F₀` and `F₁`. Its size is
//!   `1 + size(cert F₀) + size(cert F₁)`. Memoization can only shrink it, so
//!   `toll(F₀ ⋈ F₁) ≤ toll(F₀) + toll(F₁) + 1`.
//!
//! Certified: the composed certificate is valid (local checker), and polynomial toll is CLOSED
//! under iterated join (toll grows linearly in the number of joins — a fitted law). The only way a
//! family's toll goes super-polynomial is needing super-polynomially many DISTINCT sub-families
//! (decision-width) — the isolated Toll Lemma. The join step of the induction is done.

use logicaffeine_proof::cdcl::Lit;
use logicaffeine_proof::hypercube::minimal_cover_orbits;
use std::collections::HashMap;

type CanonClauses = Vec<Vec<(u32, bool)>>;

fn canon(clauses: &[Vec<(u32, bool)>]) -> CanonClauses {
    let mut out: CanonClauses = clauses
        .iter()
        .map(|c| {
            let mut lits = c.clone();
            lits.sort_unstable();
            lits.dedup();
            lits
        })
        .collect();
    out.sort();
    out.dedup();
    out
}

fn to_canon(clauses: &[Vec<Lit>]) -> CanonClauses {
    canon(
        &clauses
            .iter()
            .map(|c| c.iter().map(|l| (l.var(), l.is_positive())).collect())
            .collect::<Vec<_>>(),
    )
}

fn cofactor(clauses: &CanonClauses, x: u32, b: bool) -> CanonClauses {
    canon(
        &clauses
            .iter()
            .filter(|c| !c.iter().any(|&(v, pos)| v == x && pos == b))
            .map(|c| c.iter().copied().filter(|&(v, _)| v != x).collect())
            .collect::<Vec<_>>(),
    )
}

/// The Shannon join of two face-covers on a fresh variable `x`.
fn join(f0: &CanonClauses, f1: &CanonClauses, x: u32) -> CanonClauses {
    let mut out: Vec<Vec<(u32, bool)>> = Vec::new();
    for c in f0 {
        let mut nc = c.clone();
        nc.push((x, true)); // clause literal x ⟹ blocker sets x = 0
        out.push(nc);
    }
    for c in f1 {
        let mut nc = c.clone();
        nc.push((x, false)); // clause literal ¬x ⟹ blocker sets x = 1
        out.push(nc);
    }
    canon(&out)
}

#[derive(Clone, Debug)]
enum Node {
    Leaf(CanonClauses),
    Internal { clauses: CanonClauses, var: u32, lo: usize, hi: usize },
}

fn node_clauses(nodes: &[Node], id: usize) -> &CanonClauses {
    match &nodes[id] {
        Node::Leaf(c) => c,
        Node::Internal { clauses, .. } => clauses,
    }
}

fn dag_unfold(n: usize, clauses: &CanonClauses) -> Option<(usize, Vec<Node>)> {
    let mut nodes = Vec::new();
    let mut memo: HashMap<(usize, CanonClauses), Option<usize>> = HashMap::new();
    fn go(
        depth: usize,
        n: usize,
        clauses: CanonClauses,
        nodes: &mut Vec<Node>,
        memo: &mut HashMap<(usize, CanonClauses), Option<usize>>,
    ) -> Option<usize> {
        if let Some(&h) = memo.get(&(depth, clauses.clone())) {
            return h;
        }
        let r = if clauses.iter().any(|c| c.is_empty()) {
            let id = nodes.len();
            nodes.push(Node::Leaf(clauses.clone()));
            Some(id)
        } else if depth == n {
            None
        } else {
            let x = depth as u32;
            let lo = go(depth + 1, n, cofactor(&clauses, x, false), nodes, memo);
            let hi = go(depth + 1, n, cofactor(&clauses, x, true), nodes, memo);
            match (lo, hi) {
                (Some(lo), Some(hi)) => {
                    let id = nodes.len();
                    nodes.push(Node::Internal { clauses: clauses.clone(), var: x, lo, hi });
                    Some(id)
                }
                _ => None,
            }
        };
        memo.insert((depth, clauses), r);
        r
    }
    let root = go(0, n, clauses.clone(), &mut nodes, &mut memo)?;
    Some((root, nodes))
}

fn check(nodes: &[Node]) -> bool {
    nodes.iter().all(|node| match node {
        Node::Leaf(c) => c.iter().any(|cl| cl.is_empty()),
        Node::Internal { clauses, var, lo, hi } => {
            *node_clauses(nodes, *lo) == cofactor(clauses, *var, false)
                && *node_clauses(nodes, *hi) == cofactor(clauses, *var, true)
        }
    })
}

/// Compose a certificate of `F₀ ⋈ F₁` from the two sub-certificates: shift `F₁`'s ids, add one
/// fresh root. The join contributes exactly one node.
fn compose(
    join_clauses: &CanonClauses,
    x: u32,
    d0: (usize, Vec<Node>),
    d1: (usize, Vec<Node>),
) -> (usize, Vec<Node>) {
    let (root0, nodes0) = d0;
    let (root1, nodes1) = d1;
    let off = nodes0.len();
    let mut nodes = nodes0;
    for node in nodes1 {
        nodes.push(match node {
            Node::Leaf(c) => Node::Leaf(c),
            Node::Internal { clauses, var, lo, hi } => {
                Node::Internal { clauses, var, lo: lo + off, hi: hi + off }
            }
        });
    }
    let root = nodes.len();
    nodes.push(Node::Internal { clauses: join_clauses.clone(), var: x, lo: root0, hi: root1 + off });
    (root, nodes)
}

/// **Join adds exactly one node, and the composed certificate is valid.** For every pair of
/// `n = 2` families, the join into an `n = 3` family gets a composed certificate of size
/// `1 + s₀ + s₁` that passes the zero-trust local checker; the memoized unfolding of the same join
/// is no larger (subadditivity — the twist is toll-cheap).
#[test]
fn the_join_operation_has_additive_toll_and_the_composed_certificate_is_valid() {
    let fams: Vec<CanonClauses> =
        minimal_cover_orbits(2).iter().map(|c| to_canon(&c.clauses())).collect();
    let x = 2u32;
    let mut checked = 0usize;
    for f0 in &fams {
        for f1 in &fams {
            let (r0, n0) = dag_unfold(2, f0).expect("f0 is UNSAT");
            let (r1, n1) = dag_unfold(2, f1).expect("f1 is UNSAT");
            let (s0, s1) = (n0.len(), n1.len());
            let j = join(f0, f1, x);
            let (root, nodes) = compose(&j, x, (r0, n0), (r1, n1));
            assert_eq!(nodes.len(), 1 + s0 + s1, "the join contributes exactly one node");
            assert_eq!(*node_clauses(&nodes, root), j, "the root carries the join");
            assert!(check(&nodes), "the composed certificate passes the local checker");
            let (_, memoized) = dag_unfold(3, &j).expect("the join is UNSAT");
            assert!(
                memoized.len() <= 1 + s0 + s1,
                "toll(F₀ ⋈ F₁) = {} ≤ 1 + {s0} + {s1} — join adds constant toll",
                memoized.len()
            );
            checked += 1;
        }
    }
    eprintln!(
        "join-toll: {checked} family pairs joined; composed size = 1 + s₀ + s₁ exactly, locally \
         re-checked; memoized ≤ that (subadditive) — the twist operation is toll-cheap"
    );
}

/// **Polynomial toll is CLOSED under iterated join — the induction step.** A family built by `k`
/// joins with a constant-toll base has toll `≤ c·k = O(k)`, certified by construction: the toll
/// grows LINEARLY in `k` (constant first differences — a fitted linear law), every certificate
/// locally re-checked. Any family reachable by polynomially many joins from constant-toll bases
/// has polynomial toll; only the distinct-cofactor count (decision-width) can break it — the
/// isolated Toll Lemma.
#[test]
fn polynomial_toll_is_closed_under_iterated_join() {
    let base1: CanonClauses = canon(&vec![vec![(0u32, true)], vec![(0u32, false)]]);
    let mut fam = base1.clone();
    let mut cur_vars = 1usize;
    let mut sizes: Vec<(usize, usize)> = Vec::new();
    for k in 1..=8usize {
        let x = cur_vars as u32;
        fam = join(&fam, &base1, x);
        cur_vars += 1;
        let (_, nodes) = dag_unfold(cur_vars, &fam).expect("the iterated join is UNSAT");
        assert!(check(&nodes), "k={k}: the iterated-join certificate re-checks");
        sizes.push((k, nodes.len()));
    }
    let diffs: Vec<i64> = sizes.windows(2).map(|w| w[1].1 as i64 - w[0].1 as i64).collect();
    assert!(
        diffs.windows(2).all(|w| w[0] == w[1]),
        "the iterated-join toll is a FITTED LINEAR law: sizes {sizes:?}, first differences {diffs:?}"
    );
    eprintln!(
        "closure under join: iterated-join toll sizes {sizes:?} (constant first differences = \
         linear in k) — polynomial toll is CLOSED under the twist; k joins from constant bases ⟹ \
         O(k) toll"
    );
}
