//! Build-time stencil extraction.
//!
//! Compiles `stencils/int_stencils.rs` to an object file with `rustc
//! --emit=obj` (no linker involved, so this works for ANY installed target),
//! then extracts every `logos_stencil_*` symbol's machine code and relocation
//! records, classifying each relocation against a per-format whitelist. Two
//! hard gates run here so regressions fail the BUILD, never silently at
//! runtime:
//!
//! - **Leaf purity**: a relocation targeting anything but a recognized hole
//!   symbol (`logos_hole_cont_N` / `LOGOS_HOLE_I64_N`) is an error — stencils
//!   must be self-contained.
//! - **Tail calls**: every continuation-hole site must decode as an
//!   UNCONDITIONAL branch (`b` on aarch64, `jmp` on x86-64), confirming LLVM
//!   emitted the CPS chain as sibling calls.

use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

use object::{Object, ObjectSection, ObjectSymbol, RelocationTarget};

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let gen_path = out_dir.join("stencils.rs");
    let target = env::var("TARGET").unwrap();

    // The JIT is native-only; for wasm just emit an empty table so the
    // include! (compiled out for wasm anyway) always resolves.
    if target.contains("wasm32") {
        fs::write(
            &gen_path,
            "/// Empty on wasm (the JIT is native-only).\npub const ADD_STENCIL: &[u8] = &[];\n/// Empty on wasm (the JIT is native-only).\npub static STENCILS: &[Stencil] = &[];\n",
        )
        .unwrap();
        return;
    }

    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let stencil_src = manifest.join("stencils/int_stencils.rs");
    println!("cargo:rerun-if-changed={}", stencil_src.display());
    println!("cargo:rerun-if-changed=build.rs");

    let obj_path = out_dir.join("int_stencils.o");
    let rustc = env::var("RUSTC").unwrap_or_else(|_| "rustc".to_string());
    let status = Command::new(&rustc)
        .args([
            "-C",
            "opt-level=2",
            "-C",
            "panic=abort",
            "-C",
            "codegen-units=1",
            "--emit=obj",
            "--crate-type=lib",
            "--target",
            &target,
            "-o",
        ])
        .arg(&obj_path)
        .arg(&stencil_src)
        .status()
        .expect("failed to invoke rustc to compile stencils");
    assert!(status.success(), "rustc stencil compilation failed");

    let data = fs::read(&obj_path).expect("read object file");
    let file = object::File::parse(&*data).expect("parse object file");
    let is_aarch64 = target.starts_with("aarch64");

    // Collect every stencil symbol with its section extent.
    struct SymExtent {
        name: String,
        section: object::SectionIndex,
        addr: u64,
        size: u64,
    }
    let mut stencil_syms: Vec<SymExtent> = Vec::new();
    for sym in file.symbols() {
        let raw = match sym.name() {
            Ok(n) => n,
            Err(_) => continue,
        };
        let name = raw.strip_prefix('_').unwrap_or(raw);
        if !name.starts_with("logos_stencil_") {
            continue;
        }
        let section = match sym.section_index() {
            Some(s) => s,
            None => continue,
        };
        stencil_syms.push(SymExtent { name: name.to_string(), section, addr: sym.address(), size: sym.size() });
    }
    assert!(!stencil_syms.is_empty(), "no logos_stencil_* symbols found");

    // Mach-O symbols frequently report size 0; derive extents from the next
    // symbol in the same section, falling back to the section end.
    for i in 0..stencil_syms.len() {
        if stencil_syms[i].size == 0 {
            let section = file.section_by_index(stencil_syms[i].section).unwrap();
            let mut end = section.address() + section.data().unwrap().len() as u64;
            for s in file.symbols() {
                if s.section_index() == Some(stencil_syms[i].section) {
                    let a = s.address();
                    if a > stencil_syms[i].addr && a < end {
                        end = a;
                    }
                }
            }
            stencil_syms[i].size = end - stencil_syms[i].addr;
        }
    }

    let mut out = String::new();
    out.push_str("// GENERATED by build.rs — extracted stencil table.\n");

    let mut table_entries: Vec<String> = Vec::new();
    for sym in &stencil_syms {
        let section = file.section_by_index(sym.section).expect("section");
        let sect_data = section.data().expect("section data");
        let sect_addr = section.address();
        let start = (sym.addr - sect_addr) as usize;
        let code = &sect_data[start..start + sym.size as usize];

        // Gather + classify this symbol's relocations (function-relative).
        let mut relocs: Vec<(u32, String, String, i64)> = Vec::new();
        let mut pending_macho_addend: i64 = 0;
        for (off, reloc) in section.relocations() {
            if off < sym.addr || off >= sym.addr + sym.size {
                continue;
            }
            let fn_off = (off - sym.addr) as u32;

            // Mach-O ARM64_RELOC_ADDEND pairs with the FOLLOWING reloc.
            if let object::RelocationFlags::MachO { r_type, .. } = reloc.flags() {
                if is_aarch64 && r_type == 10 {
                    pending_macho_addend = reloc.addend();
                    continue;
                }
            }
            let mut addend = if pending_macho_addend != 0 {
                std::mem::take(&mut pending_macho_addend)
            } else {
                reloc.addend()
            };
            // Normalize PC-relative addends so the runtime patcher computes a
            // uniform `disp = target + addend - field_address`:
            // - ELF already bakes the -4 (rip-after-disp) into the addend.
            // - Mach-O x86 pcrel relocs use rip = field + 4 with addend 0.
            // - COFF REL32_N additionally encodes N trailing bytes in the type.
            match reloc.flags() {
                object::RelocationFlags::MachO { r_type, r_pcrel: true, .. } if !is_aarch64 => {
                    let _ = r_type;
                    addend -= 4;
                }
                object::RelocationFlags::Coff { typ } if (4..=9).contains(&typ) => {
                    addend -= 4 + (typ as i64 - 4);
                }
                _ => {}
            }

            let (target_name, via_import) = match reloc.target() {
                RelocationTarget::Symbol(idx) => {
                    let s = file.symbol_by_index(idx).expect("reloc target symbol");
                    let raw = s.name().expect("reloc target name");
                    // COFF expresses GOT-style indirection in the SYMBOL:
                    // `__imp_x` (MSVC import slot) or `.refptr.x` (MinGW
                    // reference-pointer stub) — both are pointer slots for x.
                    if let Some(stripped) = raw.strip_prefix("__imp_") {
                        (stripped.to_string(), true)
                    } else if let Some(stripped) = raw.strip_prefix(".refptr.") {
                        (stripped.to_string(), true)
                    } else {
                        (raw.strip_prefix('_').unwrap_or(raw).to_string(), false)
                    }
                }
                other => panic!("stencil '{}': unsupported reloc target {:?}", sym.name, other),
            };

            let hole = classify_hole(&sym.name, &target_name);
            let kind = classify_kind(
                &sym.name,
                &target_name,
                code,
                fn_off,
                reloc.flags(),
                is_aarch64,
                via_import,
            );

            // Tail-call gate: continuation sites must be unconditional branches.
            if hole.starts_with("HoleId::Cont") {
                assert_tail_call(&sym.name, code, fn_off, &kind, is_aarch64);
            }

            relocs.push((fn_off, kind, hole, addend));
        }
        relocs.sort_by_key(|r| r.0);

        let reloc_src: Vec<String> = relocs
            .iter()
            .map(|(off, kind, hole, addend)| {
                format!("Reloc {{ offset: {off}, kind: {kind}, target: {hole}, addend: {addend} }}")
            })
            .collect();

        let const_name = sym.name.replace("logos_stencil_", "ST_").to_uppercase();
        out.push_str(&format!(
            "/// Extracted `{}` stencil ({} bytes, {} relocs).\n\
             pub static {}: Stencil = Stencil {{ name: \"{}\", code: &{:?}, relocs: &[{}] }};\n",
            sym.name,
            code.len(),
            relocs.len(),
            const_name,
            sym.name,
            code,
            reloc_src.join(", ")
        ));
        table_entries.push(const_name);

        // Back-compat: the relocation-free leaf used by the headline test.
        if sym.name == "logos_stencil_add" {
            assert!(relocs.is_empty(), "logos_stencil_add must stay relocation-free");
            out.push_str(&format!(
                "/// The relocation-free leaf-add stencil (headline smoke test).\n\
                 pub const ADD_STENCIL: &[u8] = &{:?};\n",
                code
            ));
        }
    }

    out.push_str("/// Every extracted stencil, in object-file order.\npub static STENCILS: &[&Stencil] = &[");
    for e in &table_entries {
        out.push_str(&format!("&{e}, "));
    }
    out.push_str("];\n");

    fs::write(&gen_path, out).unwrap();
}

/// Map a relocation-target symbol name to its hole — the LEAF-PURITY gate.
fn classify_hole(stencil: &str, target: &str) -> String {
    if let Some(n) = target.strip_prefix("logos_hole_cont_") {
        let n: u8 = n.parse().unwrap_or_else(|_| {
            panic!("stencil '{stencil}': malformed continuation hole '{target}'")
        });
        return format!("HoleId::Cont({n})");
    }
    if let Some(n) = target.strip_prefix("LOGOS_HOLE_I64_") {
        let n: u8 = n
            .parse()
            .unwrap_or_else(|_| panic!("stencil '{stencil}': malformed const hole '{target}'"));
        return format!("HoleId::ConstI64({n})");
    }
    panic!(
        "stencil '{stencil}' references non-hole symbol '{target}' — stencils must be \
         self-contained leaves (only logos_hole_cont_N / LOGOS_HOLE_I64_N)"
    );
}

/// Normalize a format-specific relocation to our RelocKind — anything outside
/// the whitelist is a build error naming the stencil and the raw kind.
#[allow(clippy::too_many_arguments)]
fn classify_kind(
    stencil: &str,
    target: &str,
    code: &[u8],
    off: u32,
    flags: object::RelocationFlags,
    is_aarch64: bool,
    via_import: bool,
) -> String {
    match flags {
        object::RelocationFlags::MachO { r_type, .. } => {
            // ARM64_RELOC_*: BRANCH26=2 PAGE21=3 PAGEOFF12=4 GOT_LOAD_PAGE21=5
            // GOT_LOAD_PAGEOFF12=6. X86_64_RELOC_: BRANCH=2 SIGNED=1 GOT_LOAD=3
            // GOT=4 UNSIGNED=0 — distinguished by target arch via the insn.
            match r_type {
                2 => {
                    // ARM64_RELOC_BRANCH26 or X86_64_RELOC_BRANCH.
                    if is_aarch64 {
                        "RelocKind::Branch26".to_string()
                    } else {
                        "RelocKind::Rel32".to_string()
                    }
                }
                3 => {
                    if is_aarch64 {
                        assert!(
                            is_aarch64_adrp(code, off),
                            "stencil '{stencil}': PAGE21 site is not an ADRP"
                        );
                        "RelocKind::Page21".to_string()
                    } else {
                        // X86_64_RELOC_GOT_LOAD
                        "RelocKind::GotRel32".to_string()
                    }
                }
                4 => {
                    if is_aarch64 {
                        let scale = aarch64_pageoff_scale(code, off).unwrap_or_else(|| {
                            panic!("stencil '{stencil}': PAGEOFF12 site is not ADD/LDR")
                        });
                        format!("RelocKind::PageOff12 {{ scale: {scale} }}")
                    } else {
                        // X86_64_RELOC_GOT
                        "RelocKind::GotRel32".to_string()
                    }
                }
                5 => "RelocKind::GotPage21".to_string(),
                6 => "RelocKind::GotPageOff12".to_string(),
                0 => "RelocKind::Abs64".to_string(),
                1 => "RelocKind::Rel32".to_string(),
                other => panic!(
                    "stencil '{stencil}' (target '{target}'): unsupported Mach-O reloc type {other}"
                ),
            }
        }
        object::RelocationFlags::Elf { r_type } => match r_type {
            // x86_64
            1 => "RelocKind::Abs64".to_string(),
            2 | 4 => "RelocKind::Rel32".to_string(),
            9 | 41 | 42 => "RelocKind::GotRel32".to_string(),
            // aarch64
            257 => "RelocKind::Abs64".to_string(),
            282 | 283 => "RelocKind::Branch26".to_string(),
            275 => "RelocKind::Page21".to_string(),
            277 => "RelocKind::PageOff12 { scale: 0 }".to_string(),
            286 => "RelocKind::PageOff12 { scale: 3 }".to_string(),
            311 => "RelocKind::GotPage21".to_string(),
            312 => "RelocKind::GotPageOff12".to_string(),
            other => panic!(
                "stencil '{stencil}' (target '{target}'): unsupported ELF reloc type {other}"
            ),
        },
        object::RelocationFlags::Coff { typ } => match typ {
            1 => "RelocKind::Abs64".to_string(),
            // REL32 .. REL32_5: the trailing distance folds into the addend
            // at patch time via (typ - 4). `__imp_` targets are import-table
            // (GOT-style) indirections.
            4..=9 if via_import => "RelocKind::GotRel32".to_string(),
            4..=9 => "RelocKind::Rel32".to_string(),
            other => panic!(
                "stencil '{stencil}' (target '{target}'): unsupported COFF reloc type {other}"
            ),
        },
        other => panic!("stencil '{stencil}': unsupported reloc flags {other:?}"),
    }
}

fn read_u32(code: &[u8], off: u32) -> u32 {
    let i = off as usize;
    u32::from_le_bytes([code[i], code[i + 1], code[i + 2], code[i + 3]])
}

fn is_aarch64_adrp(code: &[u8], off: u32) -> bool {
    if off as usize + 4 > code.len() {
        return false;
    }
    let insn = read_u32(code, off);
    (insn & 0x9F00_0000) == 0x9000_0000
}

/// For an arm64 lo12 site: the access-size scale (0 for ADD, log2(bytes) for
/// LDR/STR), or None when the instruction is not an arm64 lo12 form.
fn aarch64_pageoff_scale(code: &[u8], off: u32) -> Option<u8> {
    if off as usize + 4 > code.len() {
        return None;
    }
    let insn = read_u32(code, off);
    // ADD (immediate), 64-bit: sf=1 op=0 S=0 100010 …
    if (insn & 0x7F80_0000) == 0x1100_0000 {
        return Some(0);
    }
    // Load/store register (unsigned immediate): size[31:30] 111 V 01 opc …
    if (insn & 0x3B00_0000) == 0x3900_0000 {
        return Some((insn >> 30) as u8);
    }
    None
}

/// The TAIL-CALL gate: a continuation site must be an unconditional branch.
fn assert_tail_call(stencil: &str, code: &[u8], off: u32, kind: &str, is_aarch64: bool) {
    if is_aarch64 {
        assert!(
            kind.contains("Branch26"),
            "stencil '{stencil}': continuation reloc at {off} is {kind}, expected Branch26"
        );
        let insn = read_u32(code, off);
        let top6 = insn >> 26;
        assert!(
            top6 == 0b000101,
            "stencil '{stencil}': continuation at {off} is {} (insn {insn:#010x}), not a tail \
             call — rustc stopped emitting sibling calls; the stencil chain would grow the stack",
            if top6 == 0b100101 { "BL (a call)" } else { "not a branch" }
        );
    } else if kind == "RelocKind::Rel32" {
        // Direct: `jmp rel32` (E9) or a conditional `jcc rel32` (0F 8x) —
        // both transfer control without pushing a return address. A CALL
        // (E8) means rustc stopped emitting sibling calls.
        let i = off as usize;
        let opcode = code[i.checked_sub(1).expect("rel32 at offset 0")];
        let is_jmp = opcode == 0xE9;
        let is_jcc = i >= 2 && code[i - 2] == 0x0F && (opcode & 0xF0) == 0x80;
        assert!(
            is_jmp || is_jcc,
            "stencil '{stencil}': continuation at {off} has opcode {opcode:#04x}, expected JMP \
             (E9) or Jcc (0F 8x) — a CALL (E8) means rustc stopped emitting sibling calls"
        );
    } else if kind == "RelocKind::GotRel32" {
        // Indirect through the GOT: `jmp qword ptr [rip+disp]` = FF /4
        // (ModRM reg field 100). `call` would be FF /2.
        let i = off as usize;
        let opcode = code[i.checked_sub(2).expect("got jmp at offset < 2")];
        let modrm = code[i - 1];
        assert!(
            opcode == 0xFF && (modrm & 0x38) == 0x20,
            "stencil '{stencil}': continuation at {off} is {opcode:#04x} {modrm:#04x}, expected \
             an indirect JMP (FF /4) — an indirect CALL (FF /2) means rustc stopped emitting \
             sibling calls"
        );
    } else {
        panic!("stencil '{stencil}': continuation reloc at {off} is {kind}, expected Rel32/GotRel32");
    }
}
