#![cfg_attr(docsrs, feature(doc_cfg))]
#![doc = include_str!("../README.md")]

pub mod line_index;
pub mod state;
pub mod scheduler;
pub mod workspace;
pub mod flycheck;
pub mod document;
pub mod pipeline;
pub mod diagnostics;
pub mod semantic_tokens;
pub mod document_symbols;
pub mod document_highlights;
pub mod selection_ranges;
pub mod call_hierarchy;
pub mod index;
pub mod definition;
pub mod hover;
pub mod completion;
pub mod teach_md;
pub mod stdlib_docs;
pub mod references;
pub mod signature_help;
pub mod code_actions;
pub mod rename;
pub mod folding;
pub mod inlay_hints;
pub mod code_lens;
pub mod formatting;
pub mod server;
